#!/bin/bash
#PBS -Pw85
#PBS -l walltime=12:00:00
#PBS -l mem=128GB
#PBS -l ncpus=12
#PBS -j oe
#PBS -o /home/547/cxa547/logs/wrf
#PBS -q normal
#PBS -l wd
#PBS -m abe
#PBS -M craig.arthur@ga.gov.au
#PBS -v CASE
#PBS -l storage=gdata/w85+scratch/w85

module purge
source /g/data/w85/software/WRF/build.env


# Base directory for the WRF install:
WRF_ROOT=/g/data/$PROJECT/software/WRF/WRF

# Namelist for the simulation:
NAMELIST=$HOME/namelists/lestest/namelist.input.$CASE
SOUNDING=$HOME/namelists/lestest/input_sounding.$CASE

# sed command to automagically update the grid size in the namelist:
# sed -i "/^\s\(e_we\|e_sn\)/s/[0-9]\{2,\}/$NX/" $NAMELIST

# Check the executable exists before trying to run it
if [ ! -f "$WRF_ROOT/test/em_les/wrf.exe" ]; then
    echo "wrf.exe doesnt exist for em_les"
    echo "You need to compile the test case first"
    # Kill the job, reporting command not found
    exit 127
fi

# Simulation: one of the test cases available in the WRF code, or "em_real"
SIMULATION=em_les

# Where the simulation output will be stored:
RUNDIR=/scratch/$PROJECT/$USER/WRF/$CASE

cd $RUNDIR

echo $CASE
echo "Setting up test case by linking data files into the run directory"

#echo "linking namelist file"
#ln -sf $NAMELIST ./namelist.input
#ln -sf $SOUNDING ./input_sounding

# Check the wrf input file exists before trying to run
if [ ! -f "$RUNDIR/wrfinput_d01" ]; then
    echo "wrfinput_d01 doesnt exist for $CASE"
    echo "You need to run ideal.exe first"
    # Kill the job, reporting command not found
    exit 2
fi

ulimit -s unlimited


export OMP_NUM_THREADS=2
export OMP_PROC_BIND=true
NCORE=$(($PBS_NCPUS/$OMP_NUM_THREADS))
echo "Running $CASE with $PBS_NCPUS mpi ranks and $OMP_NUM_THREADS OpenMPI threads"

time mpirun -np $NCORE --map-by node:PE=$OMP_NUM_THREADS --rank-by core -report-bindings $WRF_ROOT/test/$SIMULATION/wrf.exe > $RUNDIR/wrf.$CASE.$PBS_NCPUS.log

OUT=$?
if [ $OUT -ne 0 ]; then
   echo "Execution returned non-zero exit status ($OUT)"
   echo "Check rsl.out and rsl.error files in $RUNDIR"
else
    echo "Successfully completed wrf.exe for $CASE"
    echo "Check log file at $RUNDIR/wrf.$CASE.$PBS_NCPUS.log"
fi

