#!/bin/tcsh
#PBS -Pw85
#PBS -l walltime=12:00:00
#PBS -l mem=512GB
#PBS -l ncpus=64
#PBS -j oe
#PBS -q normal
#PBS -l wd
#PBS -m abe
#PBS -M craig.arthur@ga.gov.au

module purge
module load openmpi/1.8.8
module load netcdf/4.3.3.1

limit stacksize unlimited

echo running with $PBS_NCPUS mpi ranks
time mpirun -np $PBS_NCPUS -report-bindings ./wrf.exe
